export const DUEL_TIME_LIMIT_SECONDS = 2 * 60 * 60;
export const DUEL_REQUEST_TIMEOUT_SECONDS = 72 * 60 * 60;
export const PUBLIC_DUEL_MATCH_WINDOW_SECONDS = 24 * 60 * 60;
export const MAX_CONSECUTIVE_DUEL_ABANDONS = 3;
export const DUEL_ABANDON_COOLDOWN_HOURS = 24;
export const PENDING_DUEL_POLL_INTERVAL_MS = 1_500;
export const ACTIVE_DUEL_POLL_INTERVAL_MS = 4_000;
