import {build} from 'esbuild';import {writeFile,mkdir} from 'node:fs/promises';
const result=await build({entryPoints:['src/editor/entry.ts'],bundle:true,write:false,minify:true,format:'iife',platform:'browser',target:'es2020'});
const js=result.outputFiles[0].text.replaceAll('</script','<\\/script');
const html='<!doctype html><html><head><meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src \'none\'; script-src \'unsafe-inline\'; style-src \'unsafe-inline\'; connect-src \'none\';"><style>html,body{margin:0;background:#111316;color:#f4f6f8;height:100%}.cm-editor{height:100%;font-size:15px}.cm-scroller{overflow:auto}#editor{height:100%}</style></head><body><div id="editor"></div><script>'+js+'</script></body></html>';
await mkdir('src/editor',{recursive:true});await writeFile('src/editor/document.generated.ts','// Generated by scripts/build-editor.mjs. No network resources or user data.\nexport const editorHtml = '+JSON.stringify(html)+';\n');

